# Generated by Django 6.0.1 on 2026-01-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='psy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Name')),
                ('Age', models.IntegerField(verbose_name='Age')),
                ('Specialty', models.CharField(max_length=100, verbose_name='Specialty')),
                ('Experience_Years', models.IntegerField(verbose_name='Experience Years')),
                ('Contact_Email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('Bio', models.TextField(verbose_name='Bio')),
                ('Created_At', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('Updated_At', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Psychologist',
                'verbose_name_plural': 'Psychologists',
            },
        ),
    ]
